title: "My Journey to Data Analysis"
author: "Van Nguyen"
description: "Following my Passion for <b style=\"color: #f45;\">&lt;Numbers & Logics</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false       # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "", title: Homepage}
  - {file: "index.html", title: Projects}
  - {file: "Resume.pdf", title: Resume}
  - {file: "README.md", title: About Me}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Email, icon: envelope, url: "mailto:vnguyen.rit@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/vnguyenbfb"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/van-nguyen-2b8b5817/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
